branch-defaults:
  main:
    environment: Propertybidapp-env
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: PropertyBidApp
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application