# Generated by Django 2.1.15 on 2022-02-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyManager',
        ),
    ]
