# Generated by Django 3.2.12 on 2022-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220220_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(upload_to='property/'),
        ),
    ]
