# Generated by Django 3.2.12 on 2022-02-22 18:29

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(upload_to=property.models.image_upload_path),
        ),
    ]
